// Best-effort filter to keep AI-generated "artists" off the app and promote only real artists.
// iTunes has no "AI" metadata flag, so this matches explicit AI markers in the artist/album
// name plus a maintainable blocklist of known AI music generators / accounts.

// Explicit AI indicators in an artist or album/track title.
const AI_MARKERS =
  /\b(a\.?i\.?[-\s]?(generated|cover|music|version|remix|mashup|made|powered)|generated by ai|made with ai|ai[-\s]?vocals?|artificial intelligence|suno(\s?ai)?|udio|boomy|mubert|aiva|soundraw|riffusion|chatgpt|gpt-?\d|neural cover|fake(?:\s|-)?(?:drake|vocals))\b/i;

// Known AI-music generators / channels / projects (exact-ish artist names). Extend as needed.
const AI_ARTISTS = new Set<string>([
  "suno", "suno ai", "udio", "boomy", "mubert", "aiva", "soundraw", "riffusion",
  "ai music", "ai cover", "endel",
]);

const norm = (s: string) => s.toLowerCase().trim();

/** True when the artist/album looks AI-generated and should be hidden. */
export function isLikelyAI(artist?: string | null, title?: string | null): boolean {
  const a = norm(artist ?? "");
  const t = norm(title ?? "");
  if (a && AI_ARTISTS.has(a)) return true;
  if (artist && AI_MARKERS.test(artist)) return true;
  if (title && AI_MARKERS.test(title)) return true;
  return false;
}
